name: 🐞 Bug
description: Report a bug/issue
labels: [bug]
body:
- type: textarea
  attributes:
    label: Subject of the issue
    description: Describe your issue here.
    placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: markdown
  attributes:
    value: "# Enviroment"
- type: markdown
  attributes:
    value: |
      Please provide as much information as possible in order to resolve your issue. Need help? [Find out your version](https://github.com/g3w-suite/g3w-admin#version).
- type: input
  attributes:
    label: G3W-ADMIN Version
    description: 
    placeholder: eg. v3.4.x
  validations:
    required: true
- type: input
  attributes:
    label: G3W-CLIENT Version
    description: 
    placeholder: eg. v3.4.x
  validations:
    required: false
- type: input
  attributes:
    label: Browser name
    description: 
    placeholder: eg. Chrome, Firefox, Opera, Safari, ...
  validations:
    required: true
- type: input
  attributes:
    label: Operating System
    description:
    placeholder: eg. Windows 11 Pro (desktop), Android 11 (mobile), iOS 15 (mobile), ...
  validations:
    required: true
- type: input
  attributes:
    label: Link to your project
    description: 
    placeholder: eg. https://dev.g3wsuite.it/en/map/demo-34/
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional info
    description: |
      Add any other useful information that could allow others to replicate your issue, for example:
      - **installed plugins**
      - **project structure**
      - **configuration files**
      - **self-explanatory pictures**
    placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I searched through the existing issues and this bug has never been reported before
      required: true
